### ISSUE TITLE
Question: Is this chart published?

### ISSUE THREAD

**Issue by smuda** [kubecost/openshift-helm-chart#14]
Is this chart published anywhere?

I'd like to use this chart as a subchart in my argocd-repository and it's more maintainable to be able to point to a chart that is actively maintained than copying everying locally.

**Comment by linhlam-kc** [comment]
Hi John, this chart is manually updated with specific changes (securityContext, custom values files, etc ...) for OpenShift cluster when a new version of [standard Kubecost Helm chart](https://github.com/kubecost/cost-analyzer-helm-chart) is released. We are also working and testing to merge them together (to the standard Helm chart) in the future.

**Comment by smuda** [comment]
I thought it was strange to have a separate helm chart for OpenShift/OKD. It's not that different, after all. I think I'll then wait for you to merge into the generic helm chart.
